---
node_ufw_rules:
  - port: "{{ avalanche.validator.ports.staking_port }}"
    proto: tcp
    rule: allow
    from: any
    comment: staking_port

  - port: "{{ avalanche.validator.ports.http_port }}"
    proto: tcp
    rule: allow
    from: "{{ monitor_server_dns }}"
    comment: http_port
