---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    avalanche:
      hosts:
        validator.avalanche.mainnet.encapsulate.xyz:
          type: validator
