---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    avalanche:
      hosts:
        validator.avalanche.testnet.encapsulate.xyz:
          type: validator
