---
# maintains directories and paths
node_home_dir: /opt/{{ service_identifier }}

node_bin_dir: "{{ node_home_dir }}/bin"
node_config_dir: "{{ node_home_dir }}/config"
node_data_dir: "{{ node_home_dir }}/data"
node_plugins_dir: "{{ node_home_dir }}/plugins"
node_log_dir: "{{ node_home_dir }}/log"
node_key_dir: "{{ node_home_dir }}/keys"

node_chains_config_dir: "{{ node_config_dir }}/chains"
node_chain_data_dir: "{{ node_data_dir }}/chaindata"

node_directories:
  - "{{ node_home_dir }}"
  - "{{ node_bin_dir }}"
  - "{{ node_config_dir }}"
  - "{{ node_chains_config_dir }}"
  - "{{ node_chain_data_dir }}"
  - "{{ node_data_dir }}"
  - "{{ node_plugins_dir }}"
  - "{{ node_key_dir }}"
  - "{{ node_log_dir }}"

node_config_file_path: "{{ node_config_dir }}/{{ node_config_file_name }}"
node_log_file_path: "{{ node_log_dir }}/{{ service_identifier }}.log"

node_signer_key_path: "{{ node_key_dir }}/{{ node_signer_key_file_name }}"
node_staker_key_path: "{{ node_key_dir }}/{{ node_staker_key_file_name }}"
node_staker_crt_path: "{{ node_key_dir }}/{{ node_staker_crt_file_name }}"
