---
- name: Include the network ufw vars file
  ansible.builtin.include_vars:
    file: vars/ufw_rules.yml

- name: Apply UFW rules
  ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
  loop: "{{ node_ufw_rules }}"

- name: Include user creation task for avalanche
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ node_home_dir }}"
    directories: "{{ node_directories }}"
    log_file_path: "{{ node_log_file_path }}"

- name: Include extract_binary task
  ansible.builtin.include_tasks: tasks/extract_binary.yml
  vars:
    extracted_binary_dir: "{{ node_service_default_binary_name }}-{{ avalanche[type].version }}"
    source_url: "{{ avalanche[type].source_url }}/{{ avalanche[type].version }}"
    suffix_url: "{{ node_service_default_binary_name }}-{{ ansible_system | lower }}-{{ system_architecture }}-{{ avalanche[type].version }}.tar.gz"
    binary_dest_path: "{{ node_bin_dir }}/{{ service_identifier }}"
    extracted_binary_path: "{{ extracted_binary_dir }}/{{ node_service_default_binary_name }}"

- name: Copy node configuration file
  ansible.builtin.template:
    src: "{{ env }}/config.yml.j2"
    dest: "{{ node_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service

- name: Fetch secrets from HCP Vault and save to files
  when: fetch_keys | default(false) | bool
  block:
    - name: Fetch signer key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_signer_key_file_name }}"
        secret_destination_path: "{{ node_signer_key_path }}"
        secret_type: base64

    - name: Fetch staker key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_staker_key_file_name }}"
        secret_destination_path: "{{ node_staker_key_path }}"
        secret_type: key

    - name: Fetch staker key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_staker_crt_file_name }}"
        secret_destination_path: "{{ node_staker_crt_path }}"
        secret_type: key

- name: Copy node systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
